"""initial schema

Revision ID: 32d8a0bdc39e
Revises: 
Create Date: 2026-09-17 23:07:52.252782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d8a0bdc39e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academicians')),
    sa.UniqueConstraint('full_name', name=op.f('uq_academicians_full_name'))
    )
    with op.batch_alter_table('academicians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academicians_id'), ['id'], unique=False)

    op.create_table('firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firms')),
    sa.UniqueConstraint('name', name=op.f('uq_firms_name'))
    )
    with op.batch_alter_table('firms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firms_id'), ['id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valid_year', sa.Integer(), nullable=False),
    sa.Column('tto_share_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('withholding_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('valid_year', name=op.f('uq_settings_valid_year'))
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('work_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('sira_no', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('work_done', sa.Text(), nullable=False),
    sa.Column('academician_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('invoice_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('invoice_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('withholding_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tto_share_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_after_tto_share', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_after_withholding', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('iban_snapshot', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_manually_adjusted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academician_id'], ['academicians.id'], name=op.f('fk_work_records_academician_id_academicians'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_work_records_firm_id_firms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_work_records_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_records')),
    sa.UniqueConstraint('year', 'sira_no', name='uq_work_records_year_sira_no')
    )
    with op.batch_alter_table('work_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_records_academician_id'), ['academician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_records_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_records_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_records_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_records_year'))
        batch_op.drop_index(batch_op.f('ix_work_records_project_id'))
        batch_op.drop_index(batch_op.f('ix_work_records_id'))
        batch_op.drop_index(batch_op.f('ix_work_records_firm_id'))
        batch_op.drop_index(batch_op.f('ix_work_records_academician_id'))

    op.drop_table('work_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_id'))

    op.drop_table('settings')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('firms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firms_id'))

    op.drop_table('firms')
    with op.batch_alter_table('academicians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academicians_id'))

    op.drop_table('academicians')
    # ### end Alembic commands ###
