"""add vat_rate and invoice_withholding_rate to settings

Revision ID: fab645720bcb
Revises: 32d8a0bdc39e
Create Date: 2026-09-18 14:40:43.142194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab645720bcb'
down_revision: Union[str, Sequence[str], None] = '32d8a0bdc39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_rate', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('invoice_withholding_rate', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('invoice_withholding_rate')
        batch_op.drop_column('vat_rate')

    # ### end Alembic commands ###
